// <auto-generated />
namespace AcmeCursos.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fist));
        
        string IMigrationMetadata.Id
        {
            get { return "201508312309008_Fist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
